import { z } from "zod";

// Schema describing the env vars that are exposed to the client bundle.
const clientEnvSchema = z.object({
  NEXT_PUBLIC_WEB_URL: z.string().url(),
  NEXT_PUBLIC_API_URL: z.string().url(),
  NEXT_PUBLIC_ENVIRONMENT: z.enum(["dev", "qa", "prod"]),

  // Subscription
  NEXT_PUBLIC_MONTHLY_SUBSCRIPTION_PRICE_ID: z.string().min(1),
  NEXT_PUBLIC_YEARLY_SUBSCRIPTION_PRICE_ID: z.string().min(1),
  NEXT_PUBLIC_LIFETIME_PRICE_ID: z.string().min(1),

  // Firebase config
  NEXT_PUBLIC_FIREBASE_API_KEY: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_APP_ID: z.string().min(1),
  NEXT_PUBLIC_CUSTOMER_PORTAL_LINK: z.string().min(1),
});

// Validate the env vars at build time
export const env = clientEnvSchema.parse({
  NEXT_PUBLIC_WEB_URL: process.env.NEXT_PUBLIC_WEB_URL,
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_ENVIRONMENT: process.env.NEXT_PUBLIC_ENVIRONMENT,

  // Subscription prices
  NEXT_PUBLIC_MONTHLY_SUBSCRIPTION_PRICE_ID:
    process.env.NEXT_PUBLIC_MONTHLY_SUBSCRIPTION_PRICE_ID,
  NEXT_PUBLIC_YEARLY_SUBSCRIPTION_PRICE_ID:
    process.env.NEXT_PUBLIC_YEARLY_SUBSCRIPTION_PRICE_ID,
  NEXT_PUBLIC_LIFETIME_PRICE_ID: process.env.NEXT_PUBLIC_LIFETIME_PRICE_ID,

  // Firebase config
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
    process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
    process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_CUSTOMER_PORTAL_LINK:
    process.env.NEXT_PUBLIC_CUSTOMER_PORTAL_LINK,
});

// Convenient named exports ↓ no need to dot‑access each time
export const {
  NEXT_PUBLIC_WEB_URL,
  NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_ENVIRONMENT,

  // Subscription prices
  NEXT_PUBLIC_MONTHLY_SUBSCRIPTION_PRICE_ID,
  NEXT_PUBLIC_YEARLY_SUBSCRIPTION_PRICE_ID,
  NEXT_PUBLIC_LIFETIME_PRICE_ID,

  // Firebase config
  NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_CUSTOMER_PORTAL_LINK,
} = env;

export type Env = z.infer<typeof clientEnvSchema>;
